repos:
  - repo: local
    hooks:
      - id: build-docs
        name: Build Sphinx docs
        entry: ./build_docs.sh --no-browser
        language: system
        pass_filenames: false
        always_run: true
